site_name: 'Documentation - The Tensor Algebra Compiler (taco)'
site_favicon: favicon.ico
theme_dir: 'readthedocs'
extra_css: [extra.css]
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
site_author: Apurva Shrivastava
use_directory_urls: false
pages:
    - Home: index.md
    - Python Library:
        - 'Defining Tensors': 'pytensors.md'
        - 'Computing on Tensors': 'pycomputations.md'
    - C++ Library:
        - 'Defining Tensors': 'tensors.md'
        - 'Computing on Tensors': 'computations.md'
    - Example Applications:
        - 'Scientific Computing: SpMV': 'scientific_computing.md'
        - 'Machine Learning: SDDMM': 'machine_learning.md'
        - 'Data Analytics: MTTKRP': 'data_analytics.md'
