site_name: 'Documentation - The Tensor Algebra Compiler (TACO)'
site_favicon: favicon.ico
theme_dir: 'readthedocs'
extra_css: [extra.css]
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
    - markdown.extensions.admonition
    - markdown.extensions.fenced_code
    - pymdownx.superfences
use_directory_urls: false
pages:
    - Home: index.md
    - Python Library:
        - 'Defining Tensors': 'pytensors.md'
        - 'Computing on Tensors': 'pycomputations.md'
        - 'Reference Manual': 'pyreference.md'
    - Example Applications:
        - 'Scientific Computing: SpMV': 'scientific_computing.md'
        - 'Data Analytics: MTTKRP': 'data_analytics.md'
        - 'Machine Learning: SDDMM': 'machine_learning.md'
    - Strategies for Optimization: optimization.md
    - Guide to Benchmarking: benchmarking.md
