site_name: Documentation - TACO
site_url:
site_description: Documentation for TACO - The efficient and vesatile tensor expression compiler!
site_favicon: favicon.ico
theme_dir: 'readthedocs'
repo_url: https://github.com/mit-commit/taco
repo_name: GitHub
site_author: Apurva Shrivastava
pages:
- Home: index.md
- Get Started:
    - 'Installation': 'installation.md'
    - 'Quick Start': 'quickstart.md'
- Building:
    - 'Basic Compiling Examples': 'shortcode-doc.md'
    - 'Example 1: Tensor Times Vector': 'build/tensor-vector.md'
    - 'Example 2: Another Example': 'build/tensor-vector.md'
    - 'Example 3: Canonical Decomposition': 'build/canonical-decomp.md'
- Joining The Community:
    - 'How to Join': 'social-login/configuration.md'
- Extras:
    - 'Extras': 'extras/recaptcha.md'
