site_name: Documentation - TACO
site_url:
site_description: Documentation for TACO - The efficient and vesatile tensor expression compiler!
site_favicon: favicon.ico
theme_dir: 'readthedocs'
extra_css: [extra.css]
repo_url: https://github.com/mit-commit/taco
repo_name: GitHub
site_author: Apurva Shrivastava
pages:
- Home: index.md
- Background:
    - 'Background Information': 'introduction.md'
    - 'Problem': 'problem.md'
    - 'taco': 'taco.md'
    - 'Read the Paper': 'paper.md'
- Get Setup:
    - 'Installation': 'installation.md'
    - 'Quick Start': 'quickstart.md'
- Basic Functions:
    - 'Basic Example: Tensor Times Vector': 'build/tensor-vector.md'
    - 'Mechanics: Command-Line and C++': 'mechanics.md'
- taco Usage:
    - 'Scientific Computing': 'scientificcomputing.md'
    - 'Machine Learning': 'machinelearning.md'
    - 'Data Analytics': 'dataanalytics.md'
    - 'Performance Engineering': 'performanceengineering.md'
- Joining The Community:
    - 'How to Join': 'joining.md'
